resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:c34a0fe4e512b3eee2757a28a925b184404531741421f376c3eee14edf37ba67
  name: controller
  newName: quay.io/cuppett/cloudformation-operator
