apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
  labels:
    control-plane: manager
spec:
  selector:
    matchLabels:
      control-plane: manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-keys
              key: AWS_ACCESS_KEY_ID
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-keys
              key: AWS_DEFAULT_REGION
        - name: AWS_PROFILE
          valueFrom:
            secretKeyRef:
              name: aws-keys
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-keys
              key: AWS_REGION
        - name: AWS_SDK_LOAD_CONFIG
          valueFrom:
            secretKeyRef:
              name: aws-keys
              key: AWS_SDK_LOAD_CONFIG
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-keys
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-keys
              key: AWS_SESSION_TOKEN
        - name: WATCH_NAMESPACE
          valueFrom:
            secretKeyRef:
              name: controller-flags
              key: WATCH_NAMESPACE
        args:
        - --leader-elect
        image: controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 5m
            memory: 100Mi
      serviceAccountName: manager
      terminationGracePeriodSeconds: 10