apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: aws-cloudformation-operator-manager-secret-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-cloudformation-operator-secret-role
subjects:
- kind: ServiceAccount
  name: aws-cloudformation-operator-controller-manager
  namespace: system
