apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: aws-cloudformation-operator-secret-role
rules:
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - get
