apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: manager
  name: aws-cloudformation-operator-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: manager
status:
  loadBalancer: {}
