
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cloudformation-services-k8s-aws-cuppett-dev-v1alpha1-stack
  failurePolicy: Fail
  name: vstack.kb.io
  rules:
  - apiGroups:
    - cloudformation.services.k8s.aws.cuppett.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stacks
  sideEffects: None
