
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cloudformation-cuppett-com-v1beta1-stack
  failurePolicy: Fail
  name: vstack.kb.io
  rules:
  - apiGroups:
    - cloudformation.cuppett.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stacks
  sideEffects: None
