---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudformation.services.k8s.aws.cuppett.dev
  resources:
  - stacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudformation.services.k8s.aws.cuppett.dev
  resources:
  - stacks/finalizers
  verbs:
  - update
- apiGroups:
  - cloudformation.services.k8s.aws.cuppett.dev
  resources:
  - stacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - services.k8s.aws.cuppett.dev
  resources:
  - configs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws.cuppett.dev
  resources:
  - configs/finalizers
  verbs:
  - update
- apiGroups:
  - services.k8s.aws.cuppett.dev
  resources:
  - configs/status
  verbs:
  - get
  - patch
  - update
