# permissions for controller to watch its secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-role
  namespace: system
rules:
  - apiGroups:
      - "*"
    resources:
      - secrets
    verbs:
      - get
