apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operatorframework.io/suggested-namespace: aws-cloudformation-operator
  name: aws-cloudformation-operator.v0.0.3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Config is the Schema for the configs API
      displayName: Config
      kind: Config
      name: configs.services.k8s.aws.cuppett.dev
      version: v1alpha1
    - description: Stack is the Schema for the stacks API
      displayName: Stack
      kind: Stack
      name: stacks.cloudformation.services.k8s.aws.cuppett.dev
      version: v1alpha1
  description: Manage the creation and update of AWS resources via AWS CloudFormation
  displayName: AWS CloudFormation Operator
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAyNS4wLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0ia2F0bWFuXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4Ig0KCSB2aWV3Qm94PSIwIDAgNDE3My43IDI4NTIiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDQxNzMuNyAyODUyOyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+DQo8c3R5bGUgdHlwZT0idGV4dC9jc3MiPg0KCS5zdDB7ZmlsbDojQjdDQTlEO30NCgkuc3Qxe2ZpbGw6IzNDNDkyOTt9DQoJLnN0MntmaWxsOiM3NTlDM0U7fQ0KCS5zdDN7ZmlsbDojNEI2MTJDO30NCjwvc3R5bGU+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNMTE5My41LDE5MDIuOWwxNy40LDE5LjhsODgwLjYsMjQ5LjZsNC0xNTQuN2wtNjE2LjctMTU0LjhsLTMwLjItMTAuOUwxMTkzLjUsMTkwMi45Ii8+DQo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNMjk4MC4yLDE5MDIuOWwtODk5LjQsMzAwLjJsLTIuNy0xODUuNWw2MTYuNy0xNTQuOGwyNi45LTMwLjNMMjk4MC4yLDE5MDIuOSIvPg0KPHBhdGggY2xhc3M9InN0MSIgZD0iTTIwNzguMSw4NDIuNWw2MTYuNywxNDMuN2wyNzEuMi0xMi45bDE0LjEtMjcuMmwtODU5LjMtMzA5LjNMMjA3OC4xLDg0Mi41Ii8+DQo8cGF0aCBjbGFzcz0ic3QyIiBkPSJNMTQ3OC43LDE4NjIuOGwtMjg1LjMsNDAuMWwtNy45LTI5LjZ2LTg5Nmw3LjktMzEuMmwyNTcuOCwxOS4ybDI3LjUsMjAuOVYxODYyLjgiLz4NCjxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik0yMDk1LjUsODQyLjVsLTYxNi43LDE0My43bC0yODUuMy00MC4xbDEwLjgtMTYuOWw4ODcuMy0yNTIuNUwyMDk1LjUsODQyLjUiLz4NCjxwYXRoIGNsYXNzPSJzdDMiIGQ9Ik0yMDg1LjYsMTc2LjJsLTEwMjQuMyw1MTdsMC41LDE0NjNMMjA4NS42LDI2NzNsMTUuMy0yMy4yVjIwNi4yTDIwODUuNiwxNzYuMnogTTE3ODYuMSwyMDgwLjhsLTU5Mi42LTE3Ny45DQoJVjk0Ni4ybDU5Mi42LTE3Ny44VjIwODAuOHogTTI2OTQuOSwxODYyLjhsMjg1LjMsNDAuMWwxNi0yOC4zVjk3My4zbC0xNi0yNy4ybC0yODUuMyw0MC4xVjE4NjIuOCIvPg0KPHBhdGggY2xhc3M9InN0MiIgZD0iTTIwODUuNiwyNjczbDEwMjYuMi01MTYuN2wwLjUtMTQ2M2wtMTAyNi43LTUxN1YyNjczeiBNMjM4Ny41LDc2OC40bDU5Mi42LDE3Ny44djk1Ni44bC01OTIuNiwxNzcuOVY3NjguNA0KCUwyMzg3LjUsNzY4LjR6Ii8+DQo8L3N2Zz4NCg==
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - AWS
  - CloudFormation
  links:
  - name: AWS CloudFormation Operator
    url: https://github.com/cuppett/aws-cloudformation-operator
  - name: AWS CloudFormation
    url: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html
  maintainers:
  - email: steve@cuppett.com
    name: Stephen Cuppett
  - email: scuppett@redhat.com
    name: Stephen Cuppett
  maturity: alpha
  provider:
    name: Stephen Cuppett
    url: https://github.com/cuppett
  replaces: aws-cloudformation-operator.v0.0.2
  version: 0.0.3
